### ISSUE TITLE
pnpm build失败

### ISSUE THREAD

**Issue by briteming** [hexh250786313/nextjs-antd-githubIssues-blog#36]
hi.

$ nano package.json
把这行："build": "NODE_OPTIONS=--openssl-legacy-provider next build",
改成了：
"build": "next build",

然后，
export NODE_OPTIONS=--openssl-legacy-provider

pnpm build
显示：

$ pnpm build

> next-antd-scafflod@1.0.0 build C:\Users\12799\nagb
> next build

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

info  - Using external babel configuration from C:\Users\12799\nagb\.babelrc
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (C:\Users\12799\nagb\node_modules\.pnpm\@babel+types@7.26.3\node_modules\@babel\types\lib\validators\generated\index.js:2748:35)
    at PluginPass.Program (C:\Users\12799\nagb\node_modules\.pnpm\babel-plugin-lodash@3.3.4\node_modules\babel-plugin-lodash\lib\index.js:102:44)
TypeError: Cannot read properties of undefined (reading 'exec')
    at C:\Users\12799\nagb\node_modules\.pnpm\next-size@2.1.0_next@9.5.5_react-dom@16.14.0_react@16.14.0__react@16.14.0_\node_modules\next-size\lib\asset-size-plugin.js:88:66
    at Array.map (<anonymous>)
    at C:\Users\12799\nagb\node_modules\.pnpm\next-size@2.1.0_next@9.5.5_react-dom@16.14.0_react@16.14.0__react@16.14.0_\node_modules\next-size\lib\asset-size-plugin.js:88:35
    at Array.sort (<anonymous>)
    at AssetsSizePlugin.printAssetsSize (C:\Users\12799\nagb\node_modules\.pnpm\next-size@2.1.0_next@9.5.5_react-dom@16.14.0_react@16.14.0__react@16.14.0_\node_modules\next-size\lib\asset-size-plugin.js:86:10)
    at C:\Users\12799\nagb\node_modules\.pnpm\next-size@2.1.0_next@9.5.5_react-dom@16.14.0_react@16.14.0__react@16.14.0_\node_modules\next-size\lib\asset-size-plugin.js:132:12
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\12799\nagb\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:17)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\12799\nagb\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\12799\nagb\node_modules\.pnpm\webpack@4.44.1\node_modules\webpack\lib\Compiler.js:482:27
    at C:\Users\12799\nagb\node_modules\.pnpm\neo-async@2.6.1\node_modules\neo-async\async.js:2818:7
    at done (C:\Users\12799\nagb\node_modules\.pnpm\neo-async@2.6.1\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\12799\nagb\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at C:\Users\12799\nagb\node_modules\.pnpm\webpack@4.44.1\node_modules\webpack\lib\Compiler.js:464:33
    at C:\Users\12799\nagb\node_modules\.pnpm\graceful-fs@4.2.11\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23)
info  - Creating an optimized production build
Failed to compile.

./assets/progress.less
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'minimize'. These properties are valid:
   object { url?, import?, modules?, icss?, sourceMap?, importLoaders?, esModule? }

> Build error occurred
Error: > Build failed because of webpack errors
    at build (C:\Users\12799\nagb\node_modules\.pnpm\next@9.5.5_react-dom@16.14.0_react@16.14.0__react@16.14.0\node_modules\next\dist\build\index.js:15:918)
 ELIFECYCLE  Command failed with exit code 1.

如何解决?
谢谢回复。

**Comment by hexh250786313** [comment]
@briteming Hi, 这个项目比较古老了，使用的也是早古版本的 `nextjs`（那会 vercel 还叫 now.sh 呢），`yarn.lock` 中锁定的依赖都是比较旧的包，如果你使用 pnpm/npm，可能会导致包依赖有问题

后续也不打算大幅升级/重构依赖包，所以建议你还是使用 `yarn` 来启动服务和打包（使用 yarn1，yarn2 可能也会有问题）

**Comment by briteming** [comment]
hi.

我删除了克隆下来的nextjs-antd-githubIssues-blog目录，然后重新克隆。
cd nextjs-antd-githubIssues-blog

这次我运行 yarn和yarn start均成功，然后访问http://localhost:3006/ ，能显示你的博客内容。

不过我编辑package.json, 也是把这行："build": "NODE_OPTIONS=--openssl-legacy-provider next build",
改成了：
"build": "next build",

然后，
export NODE_OPTIONS=--openssl-legacy-provider

然后运行yarn build
显示：
...
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

Done in 179.16s.
~/nextjs-antd-githubIssues-blog (master)$ find . -name index.html
./node_modules/console-browserify/test/static/index.html
./node_modules/crypto-browserify/example/index.html
./node_modules/domhandler/coverage/lcov-report/index.html
./node_modules/gitalk/dev/index.html
./node_modules/if-comp/demo/public/index.html
./node_modules/less/test/sourcemaps/index.html
./node_modules/less-vars-to-js/coverage/lcov-report/index.html
./node_modules/mute-stream/coverage/lcov-report/index.html
./node_modules/mute-stream/coverage/lcov-report/__root__/index.html
./node_modules/next/node_modules/postcss/docs/api/index.html
./node_modules/postcss/docs/api/index.html
./node_modules/resolve-url-loader/node_modules/postcss/docs/api/index.html
./node_modules/tinycolor2/index.html
./node_modules/tinycolor2/test/index.html
./node_modules/toggle-selection/example/index.html
./node_modules/tryer/test/index.html
./node_modules/unique-filename/coverage/index.html
./node_modules/unique-filename/coverage/__root__/index.html
./node_modules/vm-browserify/example/run/index.html
~/nextjs-antd-githubIssues-blog (master)$

并未找到含有index.html文件的静态网站的根目录。那么，静态网站的根目录在哪里呢？

谢谢回复！

**Comment by hexh250786313** [comment]
@briteming 这是一个服务端渲染的项目，不是纯前端的，你需要启动服务才可以访问，你 `yarn build` 后，直接 `yarn prod` 即可，具体逻辑在 `server.js` 里面，你可以看看，dev 和 prod 环境都用这个脚本来启动服务

至于纯静态，next 也提供了编译纯静态文件的功能，不过对于我的项目并不适用，因为我需要在用户请求到达以后立刻调用 github 的 api 然后插入到前端资源中再返回给用户客户端浏览器，这样可以更好地做 SEO，这种操作只有服务端渲染可以做，所以这就是为什么需要启动 node 服务

**Comment by briteming** [comment]
在哪里修改github 用户名和仓库名，修改哪个文件，毕竟我想搭建自己的博客。
谢谢回复

**Comment by briteming** [comment]
我fork了你的项目：https://github.com/briteming/nagb/ ，然后把https://github.com/briteming/nagb/ 导入到vercel.com,得到网址：https://nagb.vercel.app/，如何写自己的博文呢？

**Comment by hexh250786313** [comment]
@briteming 修改下面的文件和内容（如果提到的地址有 `https://proxy.hexh.xyz/proxy/` 前缀，则去掉这个前缀）
- `src/constants/ApiUrlForBE.js` 里面地址改成你你自己的写 issue 博文的地址
- `src/constants/ConstTypes.js` 里面的图片地址、文案、联系方式、搜索查询条件啥的全部换成你需要的
- `src/core/nextFetch.js` 里面有个 `https://pastebin.com/raw/jVFN4Tzk`，这个是用来获取 github 个人 api token 的，这个东西你不加的话 github api 会有调用次数限制，你自己网上搜一下怎么申请，我这里用一个第三方地址来获取这个 token，原因是 github 仓库不允许直接写死在代码中
- `src/components/Post/PostDetail.js` 里面有个 `clientID` 和 `clientSecret`，用来给 github 做 oauth2.0 登录用的，用于接入 github 评论，也是需要申请 github app 权限的，具体申请方式你也网上搜一下
- 最后你把这几个关键词 `hexh250786313`、`hexh250786313/Blog` 搜出来，替换成你自己的 github 用户名和仓库名就行，然后记得全局搜一下 `https://proxy.hexh.xyz/proxy/` 前缀，把这个前缀全部删掉

差不多就这些
